### ISSUE TITLE
Namespace errado?

### ISSUE THREAD

**Issue by luismilanese** [andrebian/tdd-no-mundo-real-php#1]
Prezados,
Na página 66 do livro, começa-se o código da classe MaiorPreco, porém, é dito que ela está no em `namespace CDC\Loja\Produto;` porém sua classe de teste está em `namespace CDC\Loja\Carrinho;`

Há uma divergência de namespaces, porém, pela lógica, me parece que o correto seria a implementação real estar em `namespace CDC\Loja\Produto;`

**Comment by andrebian** [comment]
@luismilanese foi feita a correção no livro e em breve os leitores serão notificados sobre a nova versão com a correção, já para os compradores do livro impresso, existe o repositório de erratas que coloco o link logo abaixo. No livro realmente estava com o namespace errado, mesmo no build mais recente. Neste repositório o erro foi corrigido no commit https://github.com/andrebian/tdd-no-mundo-real-php/commit/1a503c24a97e79e6880fdb9f49f81ebad0805b46 no entanto desatentei-me que o erro veio do código no livro.

No repositório de erratas também já foi atualizado: https://github.com/andrebian/erratas-livro-tdd-com-php/commit/4ef5ff653a4fd37682527370d36081331209d9bc
