### ISSUE TITLE
Namespace errado

### ISSUE THREAD

**Issue by luismilanese** [andrebian/tdd-no-mundo-real-php#2]
Prezados,
Notei que no livro, na página 138, logo antes da criação do método `testDeveConsultarATabelaParaCalcularValor()`, é apontado o uso da classe `RelogioDoSistema`, porém a namespace `use Loja\DataEhora` não existe. No exemplo anterior, na página 136 criamos essa classe, porém o namespace da mesma é `CDC\Exemplos`. 

Sugiro que seja revisto esse ponto.

Obrigado,
Luis

**Comment by andrebian** [comment]
@luismilanese, corrigido. Obrigado pelo feedback!

https://github.com/andrebian/erratas-livro-tdd-com-php/commit/b82366fc229447f85f497f251556848ed7bf6584

Após este commit, retornei o uso de "Tabela" no Mockery por esta abordagem ser tratada mais a frente no livro: https://github.com/andrebian/erratas-livro-tdd-com-php/commit/912e644b979a0d6f939532e2e608eba1ecaec7ba

No repositório o namespace já estava correto, foi descuido apenas ao trasncrever os códigos para o livro mesmo.
